[package]
name = "vk-oracle"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
vk-parse = { git = "https://github.com/sjb3d/vk-parse/", branch="funcpointer" }
nom = "7.1.0"
heck = "0.4.0"
take_mut = "0.2.2"
